SELECT TOP (1000) [DoctorID]
      ,[FirstName]
      ,[LastName]
      ,[Street]
      ,[City]
      ,[State]
      ,[Zip]
      ,[Phone]
      ,[AltPhone]
      ,[Email]
  FROM [HospitaIDictionary].[dbo].[Doctor]
